version: "3"

services:
  web:
    build:
      context: .
    container_name: "chat-django"
    command: sh -c "python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/multychats
    ports:
      - "8000:8000"
    env_file: ./.env
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
  redis:
    image: redis:alpine
    container_name: 'chat-redis'
    user: redis
  db:
    image: postgres:15.4-bullseye
    container_name: "chat-postgresql"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  postgres_data: