# Generated by Django 4.2.3 on 2023-07-26 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(auto_now_add=True, verbose_name='Date of Ban')),
                ('time_end', models.DateTimeField(blank=True, null=True, verbose_name='Date of Ban end')),
                ('banned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moder_bans', to=settings.AUTH_USER_MODEL, verbose_name='Banned by')),
                ('banned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to=settings.AUTH_USER_MODEL, verbose_name='Banned User')),
                ('chat_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans_of_chat', to=settings.AUTH_USER_MODEL, verbose_name='Chat Owner')),
            ],
            options={
                'verbose_name': 'Ban',
                'verbose_name_plural': 'Bans',
                'ordering': ['time_start', 'chat_owner', 'banned_user'],
            },
        ),
    ]
